const mongoose = require("mongoose");
const imageSchema = require("./shared/image.schema");

/* =========================================================
   LEGACY SUB-SCHEMAS  (unchanged — old documents keep working)
========================================================= */

const contentBlockSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ["text", "image", "link", "affiliate", "html", "video", "quote", "embed"],
      default: "text",
    },
    value: mongoose.Schema.Types.Mixed,
    meta: Object,
  },
  { _id: false }
);

const affiliateSchema = new mongoose.Schema(
  {
    title: String,
    link: String,
    buttonText: String,
    productImage: String,
    price: String,
    clicks: { type: Number, default: 0 },
    isAutoInjected: { type: Boolean, default: false },
  },
  { _id: false }
);

/* =========================================================
   NEW SUB-SCHEMAS
========================================================= */

const ctaSchema = new mongoose.Schema(
  {
    label: String,
    url: String,
    style: {
      type: String,
      enum: ["primary", "secondary", "ghost"],
      default: "primary",
    },
    openInNewTab: { type: Boolean, default: true },
  },
  { _id: false }
);

const videoSchema = new mongoose.Schema(
  {
    url: String, // youtube / vimeo / mp4
    thumbnail: imageSchema,
    title: String,
    caption: String,
    redirectUrl: String,
    provider: String, // youtube | vimeo | file | other
    duration: Number, // seconds
  },
  { _id: false }
);

const newsSchema = new mongoose.Schema(
  {
    /* ================= EXISTING FIELDS (unchanged) ================= */

    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
      index: true,
    },

    title: {
      type: String,
      required: true,
      index: true,
    },

    slug: {
      type: String,
      unique: true,
      index: true,
    },

    subtitle: String,

    description: {
      type: String,
      required: true,
    },

    contentBlocks: [contentBlockSchema],

    featuredImage: imageSchema,

    affiliateLinks: [affiliateSchema],

    sourceLinks: [String],

    externalLink: String,
    adsLink: String,

    isMainTrending: { type: Boolean, default: false },
    isSubTrending: { type: Boolean, default: false },
    homeOrder: { type: Number, default: 0 },

    isCategoryTrending: { type: Boolean, default: false },
    isCategorySubTrending: { type: Boolean, default: false },

    internalLinks: [
      {
        news: { type: mongoose.Schema.Types.ObjectId, ref: "News" },
        anchorText: String,
        isAutoLinked: { type: Boolean, default: true },
      },
    ],

    relatedNews: [{ type: mongoose.Schema.Types.ObjectId, ref: "News" }],

    seoAutoGenerated: { type: Boolean, default: true },
    seoScore: { type: Number, default: 0 },
    seoSuggestions: [
      {
        field: String,
        suggestion: String,
        applied: { type: Boolean, default: false },
      },
    ],
    seoLastOptimizedAt: Date,

    views: { type: Number, default: 0 },
    clicks: { type: Number, default: 0 },

    aiGenerated: { type: Boolean, default: false },
    autoUpdateEnabled: { type: Boolean, default: true },
    lastAutoUpdatedAt: Date,

    seoTitle: String,
    seoDescription: String,
    seoKeywords: [String],

    createdBy: {
      type: String,
      enum: ["admin", "ai", "import"],
      default: "ai",
    },

    status: {
      type: String,
      // "scheduled" and "trash" are additive; existing values untouched
      enum: ["draft", "published", "archived", "scheduled", "trash"],
      default: "published",
      index: true,
    },

    /* ================= NEW: CONTENT ================= */

    // Rich HTML produced by the editor (sanitised, formatting preserved).
    // `contentBlocks` stays authoritative for legacy articles; the frontend
    // renders `content` when present and falls back to blocks otherwise.
    content: { type: String, default: "" },

    // plain-text projection of `content`, used for search + read time
    contentText: { type: String, default: "", select: false },

    shortDescription: String, // alias-ish of `description`, kept separate
    longDescription: String,

    excerpt: String,

    /* ================= NEW: TAXONOMY ================= */

    subCategory: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      default: null,
      index: true,
    },

    tags: [{ type: mongoose.Schema.Types.ObjectId, ref: "Tag", index: true }],

    // free-text mirror of tag names — survives tag deletion, used by import
    tagNames: [String],

    /* ================= NEW: AUTHOR ================= */

    author: {
      name: { type: String, default: "" },
      slug: String,
      image: imageSchema,
      bio: String,
      designation: String,
      email: String,
      redirectUrl: String,
      social: {
        twitter: String,
        instagram: String,
        linkedin: String,
        website: String,
      },
    },

    /* ================= NEW: EDITORIAL FLAGS ================= */

    featured: { type: Boolean, default: false, index: true },
    trending: { type: Boolean, default: false, index: true },
    popular: { type: Boolean, default: false, index: true },
    breakingNews: { type: Boolean, default: false, index: true },
    editorsPick: { type: Boolean, default: false, index: true },

    priority: { type: Number, default: 0, index: true },

    /* ================= NEW: PUBLISHING ================= */

    publishedDate: { type: Date, default: Date.now, index: true },
    scheduledAt: { type: Date, default: null, index: true },
    updatedDate: Date,

    readTime: { type: Number, default: 0 }, // minutes

    /* ================= NEW: ENGAGEMENT ================= */

    likes: { type: Number, default: 0 },
    shareCount: { type: Number, default: 0 },
    bookmarks: { type: Number, default: 0 },

    /* ================= NEW: LOCALISATION ================= */

    language: { type: String, default: "en" },
    country: String,
    region: String, // e.g. "Asia", "Europe" — powers region browsing
    destination: String, // free-text place name for travel content

    /* ================= NEW: SOURCE / ATTRIBUTION ================= */

    sourceName: String,
    sourceUrl: String,
    canonicalUrl: String,

    /* ================= NEW: SEO ================= */

    metaTitle: String,
    metaDescription: String,
    focusKeyword: String,

    robots: {
      type: String,
      default: "index, follow",
    },

    ogImage: imageSchema,
    twitterImage: imageSchema,

    // JSON-LD. Mixed so admins can paste any schema.org object.
    // NOTE: must not be called `schema` — that path name shadows `doc.schema`
    // and breaks Mongoose's array casting. The API still accepts `schema` as an
    // input alias.
    schemaMarkup: { type: mongoose.Schema.Types.Mixed, default: null },

    /* ================= NEW: MEDIA ================= */

    gallery: [imageSchema],

    videos: [videoSchema],

    /* ================= NEW: CONVERSION ================= */

    cta: ctaSchema,

    // per-article ad overrides
    advertisement: {
      code: String,
      position: String,
      enabled: { type: Boolean, default: true },
    },

    /* ================= NEW: IMPORT BOOKKEEPING ================= */

    importBatchId: { type: String, index: true, default: null },
    importRowRef: String,

    /* ================= NEW: SOFT DELETE ================= */

    deletedAt: { type: Date, default: null, index: true },
  },
  { timestamps: true }
);

/* =========================================================
   INDEXES
========================================================= */

newsSchema.index({ status: 1, publishedDate: -1 });
newsSchema.index({ category: 1, status: 1, publishedDate: -1 });
newsSchema.index({ title: "text", description: "text", contentText: "text" });

/* =========================================================
   DERIVED FIELDS
========================================================= */

const WORDS_PER_MINUTE = 200;

const stripHtml = (html = "") =>
  String(html)
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

// Mongoose 9 middleware is promise-based — no `next` callback.
newsSchema.pre("save", function computeDerived() {
  // plain-text projection (content first, legacy blocks as fallback)
  if (this.isModified("content") || this.isModified("contentBlocks")) {
    const fromContent = stripHtml(this.content || "");
    const fromBlocks = (this.contentBlocks || [])
      .map((b) => (typeof b.value === "string" ? b.value : ""))
      .join(" ");

    this.contentText = stripHtml(`${fromContent} ${fromBlocks}`);
  }

  // read time — never overwrite an explicit admin value
  if (!this.readTime || this.isModified("content") || this.isModified("contentBlocks")) {
    const words = (this.contentText || "").split(/\s+/).filter(Boolean).length;
    this.readTime = Math.max(1, Math.ceil(words / WORDS_PER_MINUTE));
  }

  if (this.isModified() && !this.isNew) {
    this.updatedDate = new Date();
  }
});

module.exports = mongoose.models.News || mongoose.model("News", newsSchema);
module.exports.stripHtml = stripHtml;
